title: CV | Abdellah Ramadan
description:  Simple CV showing my career path.
url: https://abdellahrk.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
